### ISSUE TITLE
getting 'com.synthbot.audioplugin.vst.JVstLoadException: The plugin bundle does not exist'

### ISSUE THREAD

**Issue by weepy** [mhroth/jvsthost#1]
Hi I'm trying to run: 

<pre>
java -jar JVstHost.jar ~/Library/Audio/Plug-Ins/VST/mda\ DX10.vst
</pre>

(I have the right file there), but I keep getting: <code>com.synthbot.audioplugin.vst.JVstLoadException: The plugin bundle does not exist.</code>

Not really sure what this means ?

**Comment by mhroth** [comment]
What platform are you running on? OS X or Windows?

**Comment by weepy** [comment]
OSX

**Comment by weepy** [comment]
Do I need to do the 'buildJvh.sh' build step ?

**Comment by weepy** [comment]
ok - so it turns out that the VST instrument I was using (mda DX10 via google) wasn't working anyway. Do you know of a version of mda DX10 that works on Leopard ?
Edit: for the record - the plugins here _do_ work http://mda.smartelectronix.com/vst/mda_vst_ub.zip
